@server=http://localhost:3000
@token = {{signin.response.body.token}}

### Criação de usuário
POST {{server}}/api/createUser
Content-Type: application/json

{
  "name": "pd0t",
  "email": "pd0t@gmail.com",
  "password": "123456"
}
###

### Login e captura do token
# @name signin
POST {{server}}/api/signin
Content-Type: application/json

{
  "email": "pd0t@gmail.com",
  "password": "123456"
}
###

### GET all traffic usando o token capturado
GET {{server}}/api/traffic
Authorization: Bearer {{token}}
Content-Type: application/json
###

### POST /api/traffic usando o token capturado
POST {{server}}/api/traffic
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "source_ip": "192.168.1.5",
  "destination_ip": "192.168.1.6",
  "protocol": "HTTP",
  "user_id": 1
}
###

### GET all users usando o token capturado
GET {{server}}/api/users/6
Authorization: Bearer {{token}}
Content-Type: application/json
###